version: 2

builds:
  - main: ./cmd/main.go
    binary: obligacje
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

dockers_v2:
  - images:
      - "ghcr.io/maciekmm/obligacje"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    dockerfile: Dockerfile.goreleaser
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/maciekmm/obligacje"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
